### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by paulo-roger** [leahneukirchen/dosfetch#1]
Hey :)

First thanks for you work, looks awesome.

How can I build from source?

**Comment by voltagex** [comment]
@paulo-roger the copyright string inside the uploaded exe says `Portions Copyright (c) 1983, 92 Borland` which would point to this being compiled with Turbo Pascal 7.

**Comment by paulo-roger** [comment]
Thanks, I was expecting some directions but I guess it might be easy to look it up myself.

**Comment by voltagex** [comment]
FreePascal's cross compiler can do it with `ppcross8086 fpc -XX -Pi8086 -TMSDOS -WmTiny -FuC:\FPC\3.2.2\units\msdos\8086-tiny\rtl -FuC:\FPC\3.2.2\units\msdos\8086-tiny\rtl-console dosfetch.pas` but it generates a much larger executable.
